config/routes.rb
ToDoList::Application.routes.draw do
  root to: 'static_pages#home'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  match '/signup',  to: 'users#new'
  match '/login',  to: 'sessions#new'
  match '/logout', to: 'sessions#destroy', via: :delete
  match '/users',	to: 'users#create' #maybe change this to /createuser?
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
  
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  validates :name,  presence: true, length: { maximum: 50 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  private
  
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  
  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    #@session = Session.new
  end
  
  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
	#TODO: If user is signed in, redirect to mylists page
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
	@user = User.new(params[:user])
	if @user.save
      flash[:success] = "Account created successfully! Welcome to the to-do list!"
	  redirect_to @user
	else
	  render 'new'
	end
  end
  
  def show
    # show only if it's the current user or if current user is an admin
  
    @user = User.find(params[:id])
    if @user.nil?
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<%
thisTitle = "to-do list"

if (yield(:title)) != ""
  thisTitle += " | " + yield(:title)
end
%>

<!DOCTYPE html>
<html>
<head>
  <title><%= thisTitle %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<%= yield %>

<p class="footer">
	<%= link_to_unless_current "to-do list", root_path, class: "footerlink" %> | Copyright &#169; 2013 | <%= link_to_unless_current "Help", help_path, class: "footerlink" %> | <%= link_to_unless_current "About", about_path, class: "footerlink" %>
</p>

<!-- TODO: fix so this can replace p tags -->
<!--
<ul class="footer">
	<li><%= link_to_unless_current "to-do list", root_path, class: "footerlink" %></li>
	<li>Copyright &#169; 2013</li>
	<li><%= link_to_unless_current "Help", help_path, class: "footerlink" %></li>
	<li><%= link_to_unless_current "About", about_path, class: "footerlink" %></li>
</ul>
-->

<%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><strong>*</strong> <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'about') %>
<div id="contentwrapper">
	<h1>about</h1>
	<p class="gentext">to-do list version 1.0.0.0</p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'help') %>
<div id="contentwrapper">
	<h1>help</h1>
	<p class="gentext">coming soon</p>
</div>

app/views/static_pages/home.html.erb
<div id="contentwrapper">
	<h1>to-do list</h1>
	<p class="gentext">Welcome to the to-do list app!</p>
	<div id="buttoncontainer" style="display: inline-block;">
		<%= link_to "log in!", login_path, class:"button" %>
		<%= link_to "sign up!", signup_path, class:"button" %>
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'sign up') %>
<div id="contentwrapper">
	<h1>sign up</h1>
	<p class="gentext" style="font-size: 10px; margin-bottom: 15px;">
        Already have an account? <%= link_to "Log in!", login_path %>
    </p>
	<p class="gentext">Sign up below. It's free!</p>
	<p class="gentext">All fields are required.</p>
	<p class="gentext">&nbsp;</p>
    
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.text_field :name, placeholder: "name" %>

      <%= f.text_field :email, placeholder: "email@provider.com" %>

      <%= f.password_field :password, placeholder: "password" %>

      <%= f.password_field :password_confirmation, placeholder: "confirm password" %>
      
      <div id="buttoncontainer" style="display: inline-block;">
          <%= f.submit "create", class: "button" %>
      </div>
    <% end %>
    
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1><%= @user.name %></h1>

<%= @user.email %>